import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";
import { CartProvider } from "@/components/context/CartContext";
import { Product } from "@/lib/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-CommerceApp",
  description: "Generated by create next app",
};

async function getData() {
  let user_id = cookies().get("user_id")?.value;

  if (user_id) {
    try {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_SITE_URL}api/cart?user_id=${user_id}`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      if (!res.ok) throw new Error("Failed to fetch data");
      const products = await res.json();
      return products;
    } catch (error) {
      console.log("error: ", error);
    }
  } else {
    return null;
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let products: Product[] = await getData();
  // console.log("Layout ", products)
  let totalQuantity = 0;
  if (products) {
    totalQuantity = products.reduce((acc, item) => acc + item.quantity, 0);
    totalQuantity = totalQuantity > 0 ? totalQuantity : 0;
  }

  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar cartItemsCount={totalQuantity} />
          <main className="p-12 md:py-12 md:px-24">{children}</main>
          <Footer />
          <Toaster />
        </CartProvider>
      </body>
    </html>
  );
}
